Fixtures
fixtureZero
	^ #(
	'insert into testMisc (name, value, entryOn, notes) values 
		(''key-0001'', ''value-0001'', ''2011-07-01'', ''test entry 1''), 
		(''key-0002'', ''value-0002'', ''2011-07-01'', ''test entry 2''),
		(''key-0003'', ''value-0003'', ''2011-07-01'', ''test entry 3''), 
		(''key-0004'', ''value-0004'', ''2011-07-01'', ''test entry 4''),
		(''key-0005'', ''value-0005'', ''2011-07-01'', ''test entry 5''), 
		(''key-0006'', ''value-0006'', ''2011-07-01'', ''test entry 6''),
		(''key-0007'', ''value-0007'', ''2011-07-01'', ''test entry 7''), 
		(''key-0008'', ''value-0008'', ''2011-07-01'', ''test entry 8''),
		(''key-0009'', ''value-0009'', ''2011-07-01'', ''test entry 9''), 
		(''key-0010'', ''value-0010'', ''2011-07-01'', ''test entry 10'')
		'
	)