SystemOrganization addCategory: #MySQLDriverCoreModel!
SystemOrganization addCategory: 'MySQLDriverCoreModel-Command'!
SystemOrganization addCategory: 'MySQLDriverCoreModel-Driver'!
SystemOrganization addCategory: 'MySQLDriverCoreModel-Exception'!
SystemOrganization addCategory: 'MySQLDriverCoreModel-Helper'!
SystemOrganization addCategory: 'MySQLDriverCoreModel-Net'!
SystemOrganization addCategory: 'MySQLDriverCoreModel-Packet'!
