SystemOrganization addCategory: #'MysqlDriver-Model'!
SystemOrganization addCategory: 'MysqlDriver-Model-Command'!
SystemOrganization addCategory: 'MysqlDriver-Model-Driver'!
SystemOrganization addCategory: 'MysqlDriver-Model-Exception'!
SystemOrganization addCategory: 'MysqlDriver-Model-Helper'!
SystemOrganization addCategory: 'MysqlDriver-Model-Net'!
SystemOrganization addCategory: 'MysqlDriver-Model-Packet'!
