as yet unclassified
scenarios
^
'
Statement
- should accept no param and return no result set
- should accept no param and return result set
- should accept param and return no result set
- should accept param and return result set
- should accept positive value for integers
- should accept negative value for integers
- should accept null value for for integers
- should accept positive value for reals
- should accept negative value for reals
- should accept null value for reals
- should accept chars
- should accept null value for chars
- should accept binaries
- should accept null value for binaries
- should accept blobs
- should accept nulls value for blobs
- should accept texts
- should accept nulls value for texts
- should accept times
- should accept negative value for times (typeTIME)
- should accept null value for times
'
